# utils/mapping.py

# 1. MAPEAMENTO DE FRENTES
FRENTES_PADRAO = ['B2B', 'PRUMADAS', 'FACILIDADES', 'IMPLANTAÇÃO', 'SITE', 'MANUTENÇÃO', 'BACKBONE']

MAPEAMENTO_FRENTE = {
    'B2BQUALIDADECLIENTES': 'B2B', 'B2BALIVIO': 'B2B', 'B2BDADOSREDES': 'B2B', 
    'B2BITAU': 'B2B', 'B2BBRADESCO': 'B2B', 'B2BFUST': 'B2B', 'B2BHADES': 'B2B', 
    'CORPORATIVO': 'B2B', 'B2BATACADO': 'B2B', 'EXPANSAOB2BSHOPPINGIMP': 'B2B', 
    'EXPANSÃOB2BIMPLANT': 'B2B', 'EXPANSÃOB2BPROJETO': 'B2B', 'B2BVOZAVANCADA': 'B2B', 
    'B2BFRANQUIAS': 'B2B', 'B2BSANTANDER': 'B2B', 'B2BINTRAGOV': 'B2B', 
    'B2BPRUMADA': 'B2B', 'PRUMADAFTTXVIPB2C': 'PRUMADAS', 'ALÍVIOB2BPRUMADA': 'PRUMADAS', 
    'ALIVIOPREDIALPRUMADA': 'PRUMADAS', 'PRUMADAFTTXB2CORG': 'PRUMADAS', 
    'PRUMADAS': 'PRUMADAS', 'PRUMADAFTTXB2BORG': 'PRUMADAS', 'CONDOMINIOSORGIMPLANT': 'PRUMADAS', 
    'PRUMADAFTTXVIPB2B': 'PRUMADAS', 'S.C.': 'FACILIDADES', 'FACILIDADESORGIMPLANT': 'FACILIDADES', 
    'ALIVIOIMPLANT': 'FACILIDADES', 'FACILIDADESORGPROJETO': 'FACILIDADES',
    'SITES5GIMPLANT': 'SITE', 'IMPLANTAÇÃODESITES': 'SITE', 'SITESCONCENTRADORESIMPL': 'SITE', 
    'SITES3G/4GIMPLANT': 'SITE', 'MELHORIASNAREDE': 'MANUTENÇÃO', 'MANUTENÇÃO': 'MANUTENÇÃO',
    'BACKBONENACIONALIMPLANT': 'BACKBONE', 'ELECTRICADEQUACY': 'PROJETO', 
    'SITES5GPROJETO': 'PROJETO', 'EFICIÊNCIAIMOBILIÁRIA': 'EFICIÊNCIA IMOBILIÁRIA'
}

# 2. CONTRATOS DE COLUNAS (Schema Enforcement)
COLUNAS_PADRAO_MB52 = ['Centro', 'Material', 'Utilização livre', 'Depósito', 'Val.utiliz.livre']
COLUNAS_PADRAO_ALDREI = ['SKU', 'ID', 'UF', 'OBRA', 'FRENTE_ID', 'Aliado', 'APL x DRAFT', 'APL x MEDIÇÃO']
COLUNAS_PADRAO_CENTROS = ['ID', 'Cen.']

# 3. COLUNAS OBRIGATÓRIAS NA SAÍDA
COLUNAS_SAIDA_AUDITORIA = [
    'STATUS_AUD', 'AÇÃO_AUD', 'SUGESTÃO_AUD', 'RESULTADO_OPERACIONAL',
    'CENTRO', 'QTDE LVUT', 'QTDE EXEC', 'QTDE AMED', '$ VALOR - AMED', 'POSSUI SALDO'
]

# Como o Dash mudou de aba, os dados na aba de auditoria agora podem começar da linha 0
OFFSET_DASHBOARD = 0